//! Tests for the legacy auth file import against fixtures generated by
//! scripts/gen_fixtures.py with the Python reference implementation
//! (synthetic throwaway material only).

use audible_rs::auth::legacy::{self, LegacyEncryption, LegacyError};
use secrecy::SecretString;
use serde::Deserialize;

#[derive(Deserialize)]
struct Meta {
    password: String,
}

fn fixture(name: &str) -> Vec<u8> {
    let path = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&path)
        .unwrap_or_else(|_| panic!("missing {path} — run scripts/gen_fixtures.py once"))
}

fn password() -> SecretString {
    let meta: Meta = serde_json::from_slice(&fixture("legacy_meta.json")).unwrap();
    SecretString::from(meta.password)
}

fn expected_auth_data() -> serde_json::Value {
    serde_json::from_slice(&fixture("legacy_plain.json")).unwrap()
}

#[test]
fn detects_all_fixture_variants() {
    assert_eq!(
        legacy::detect(&fixture("legacy_plain.json")),
        LegacyEncryption::Plain
    );
    assert_eq!(
        legacy::detect(&fixture("legacy_encrypted_json.json")),
        LegacyEncryption::Json
    );
    assert_eq!(
        legacy::detect(&fixture("legacy_encrypted_bytes.bin")),
        LegacyEncryption::Bytes
    );
}

#[test]
fn reads_plain_file_without_password() {
    let data = legacy::read(&fixture("legacy_plain.json"), None).unwrap();
    assert_eq!(data, expected_auth_data());
}

#[test]
fn reads_json_encrypted_file() {
    let data = legacy::read(&fixture("legacy_encrypted_json.json"), Some(&password())).unwrap();
    assert_eq!(data, expected_auth_data());
}

#[test]
fn reads_bytes_encrypted_file() {
    let data = legacy::read(&fixture("legacy_encrypted_bytes.bin"), Some(&password())).unwrap();
    assert_eq!(data, expected_auth_data());
}

#[test]
fn encrypted_file_without_password_is_rejected() {
    let result = legacy::read(&fixture("legacy_encrypted_json.json"), None);
    assert!(matches!(result, Err(LegacyError::PasswordRequired)));
}

#[test]
fn wrong_password_fails() {
    let wrong = SecretString::from("definitely-wrong");
    for file in ["legacy_encrypted_json.json", "legacy_encrypted_bytes.bin"] {
        let result = legacy::read(&fixture(file), Some(&wrong));
        assert!(
            matches!(
                result,
                Err(LegacyError::Crypto(_) | LegacyError::InvalidPlaintext)
            ),
            "expected decryption failure for {file}"
        );
    }
}
