//! Golden tests for request signing: byte-for-byte comparison against
//! fixtures generated by `scripts/gen_fixtures.py` from the Python
//! reference implementation (synthetic throwaway keys only).

use audible_rs::auth::signing::{ADP_ALG, RequestSigner};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    adp_token: String,
    device_private_key: String,
    timestamp: String,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    method: String,
    path: String,
    body: String,
    expected_headers: ExpectedHeaders,
}

#[derive(Deserialize)]
struct ExpectedHeaders {
    #[serde(rename = "x-adp-token")]
    adp_token: String,
    #[serde(rename = "x-adp-alg")]
    alg: String,
    #[serde(rename = "x-adp-signature")]
    signature: String,
}

fn load_fixture() -> Fixture {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/signing.json");
    let raw = std::fs::read_to_string(path)
        .expect("missing tests/fixtures/signing.json — run scripts/gen_fixtures.py once");
    serde_json::from_str(&raw).expect("invalid signing fixture")
}

#[test]
fn signing_matches_python_reference() {
    let fixture = load_fixture();
    let signer = RequestSigner::new(&fixture.device_private_key, fixture.adp_token.clone())
        .expect("fixture key must parse");

    assert!(!fixture.cases.is_empty());
    for case in &fixture.cases {
        let headers = signer.sign_request_at(
            &case.method,
            &case.path,
            case.body.as_bytes(),
            &fixture.timestamp,
        );

        let expected = &case.expected_headers;
        assert_eq!(
            headers.adp_token.as_bytes(),
            expected.adp_token.as_bytes(),
            "x-adp-token mismatch in case {}",
            case.name
        );
        assert_eq!(
            headers.alg.as_bytes(),
            expected.alg.as_bytes(),
            "x-adp-alg mismatch in case {}",
            case.name
        );
        assert_eq!(
            headers.signature.as_bytes(),
            expected.signature.as_bytes(),
            "x-adp-signature mismatch in case {}",
            case.name
        );
    }
}

#[test]
fn fixture_uses_expected_algorithm() {
    let fixture = load_fixture();
    for case in &fixture.cases {
        assert_eq!(case.expected_headers.alg, ADP_ALG, "case {}", case.name);
        assert!(
            case.expected_headers
                .signature
                .ends_with(&format!(":{}", fixture.timestamp)),
            "signature of case {} must end with the fixture timestamp",
            case.name
        );
    }
}
