//! Widevine license protocol types, generated by `prost` at build time from
//! `proto/license_protocol.proto` (see `build.rs`). This is machine-generated;
//! do not edit. Only the messages the client actually uses are referenced from
//! [`super::client`].

#![allow(
    clippy::all,
    clippy::pedantic,
    missing_docs,
    rustdoc::all,
    non_snake_case
)]

include!(concat!(env!("OUT_DIR"), "/pywidevine_license_protocol.rs"));
