//! `metadata1` for the scripted login — the encrypted device-context field
//! Amazon's sign-in form expects. It is XXTEA (fixed 128-bit key) over
//! `CRC32_HEX#json`, base64'd with an `ECdITeCs:` prefix. Key and algorithm
//! are verified against a live captured value. The field is optional (the form
//! also accepts none / `false`), but including it reduces captcha frequency.

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as BASE64;

/// 128-bit XXTEA key (`struct.unpack("IIII", METADATA_KEY)`, little-endian).
const KEY: [u32; 4] = [
    u32::from_le_bytes([0x61, 0x03, 0x8f, 0x70]),
    u32::from_le_bytes([0x34, 0x18, 0x97, 0x99]),
    u32::from_le_bytes([0x3a, 0xeb, 0xe7, 0x8b]),
    u32::from_le_bytes([0x85, 0x97, 0x24, 0x34]),
];

const DELTA: u32 = 0x9E37_79B9;

fn mx(z: u32, y: u32, sum: u32, p: usize, e: u32, key: &[u32; 4]) -> u32 {
    (((z >> 5) ^ (y << 2)).wrapping_add((y >> 3) ^ (z << 4)))
        ^ ((sum ^ y).wrapping_add(key[((p as u32 & 3) ^ e) as usize] ^ z))
}

/// XXTEA encrypt, in place (mod-2^32 arithmetic; matches the reference's
/// outer-only `u32()` wrapping because XOR/low-32-bit identities hold).
fn xxtea_encrypt(v: &mut [u32], key: &[u32; 4]) {
    let n = v.len();
    if n < 2 {
        return;
    }
    let rounds = 6 + 52 / n;
    let mut sum: u32 = 0;
    let mut z = v[n - 1];
    for _ in 0..rounds {
        sum = sum.wrapping_add(DELTA);
        let e = (sum >> 2) & 3;
        for p in 0..n - 1 {
            let y = v[p + 1];
            v[p] = v[p].wrapping_add(mx(z, y, sum, p, e, key));
            z = v[p];
        }
        let y = v[0];
        v[n - 1] = v[n - 1].wrapping_add(mx(z, y, sum, n - 1, e, key));
        z = v[n - 1];
    }
}

fn bytes_to_longs(data: &[u8]) -> Vec<u32> {
    data.chunks(4)
        .map(|chunk| {
            let mut buf = [0u8; 4];
            buf[..chunk.len()].copy_from_slice(chunk);
            u32::from_le_bytes(buf)
        })
        .collect()
}

fn longs_to_bytes(v: &[u32]) -> Vec<u8> {
    v.iter().flat_map(|x| x.to_le_bytes()).collect()
}

/// CRC-32 (IEEE / zlib / `binascii.crc32`).
fn crc32(data: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFF_FFFF;
    for &byte in data {
        crc ^= byte as u32;
        for _ in 0..8 {
            crc = if crc & 1 != 0 {
                (crc >> 1) ^ 0xEDB8_8320
            } else {
                crc >> 1
            };
        }
    }
    !crc
}

/// Encrypts a metadata JSON string into the `ECdITeCs:`-prefixed form value.
pub(crate) fn encrypt_metadata(metadata: &str) -> String {
    let object = format!("{:08X}#{metadata}", crc32(metadata.as_bytes()));
    let mut longs = bytes_to_longs(object.as_bytes());
    xxtea_encrypt(&mut longs, &KEY);
    format!("ECdITeCs:{}", BASE64.encode(longs_to_bytes(&longs)))
}

fn now_unix_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

/// Builds the metadata JSON simulating an iOS Audible-app sign-in — the static
/// template the Python `audible` lib uses (the real browser one is far richer,
/// generated by Amazon's auth JS; this simpler blob is accepted). Pass the
/// result to [`encrypt_metadata`].
pub(crate) fn meta_audible_app(user_agent: &str, oauth_url: &str) -> String {
    let now = now_unix_ms();
    serde_json::json!({
        "start": now,
        "interaction": {
            "keys": 0, "keyPressTimeIntervals": [], "copies": 0, "cuts": 0,
            "pastes": 0, "clicks": 0, "touches": 0, "mouseClickPositions": [],
            "keyCycles": [], "mouseCycles": [], "touchCycles": []
        },
        "version": "3.0.0",
        "lsUbid": "X39-6721012-8795219:1549849158",
        "timeZone": -6,
        "scripts": {
            "dynamicUrls": [
                "https://images-na.ssl-images-amazon.com/images/I/61HHaoAEflL._RC|11-BZEJ8lnL.js,01qkmZhGmAL.js,71qOHv6nKaL.js_.js?AUIClients/AudibleiOSMobileWhiteAuthSkin#mobile",
                "https://images-na.ssl-images-amazon.com/images/I/21T7I7qVEeL._RC|21T1XtqIBZL.js,21WEJWRAQlL.js,31DwnWh8lFL.js,21VKEfzET-L.js,01fHQhWQYWL.js,51TfwrUQAQL.js_.js?AUIClients/AuthenticationPortalAssets#mobile",
                "https://images-na.ssl-images-amazon.com/images/I/0173Lf6yxEL.js?AUIClients/AuthenticationPortalInlineAssets",
                "https://images-na.ssl-images-amazon.com/images/I/211S6hvLW6L.js?AUIClients/CVFAssets",
                "https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/login/fwcim._CB454428048_.js"
            ],
            "inlineHashes": [
                -1746719145, 1334687281, -314038750, 1184642547, -137736901,
                318224283, 585973559, 1103694443, 11288800, -1611905557,
                1800521327, -1171760960, -898892073
            ],
            "elapsed": 52, "dynamicUrlCount": 5, "inlineHashesCount": 13
        },
        "plugins": "unknown||320-568-548-32-*-*-*",
        "dupedPlugins": "unknown||320-568-548-32-*-*-*",
        "screenInfo": "320-568-548-32-*-*-*",
        "capabilities": {
            "js": {
                "audio": true, "geolocation": true, "localStorage": "supported",
                "touch": true, "video": true, "webWorker": true
            },
            "css": {
                "textShadow": true, "textStroke": true, "boxShadow": true,
                "borderRadius": true, "borderImage": true, "opacity": true,
                "transform": true, "transition": true
            },
            "elapsed": 1
        },
        "referrer": "",
        "userAgent": user_agent,
        "location": oauth_url,
        "webDriver": null,
        "history": { "length": 1 },
        "gpu": { "vendor": "Apple Inc.", "model": "Apple A9 GPU", "extensions": [] },
        "math": {
            "tan": "-1.4214488238747243",
            "sin": "0.8178819121159085",
            "cos": "-0.5753861119575491"
        },
        "performance": { "timing": {
            "navigationStart": now, "unloadEventStart": 0, "unloadEventEnd": 0,
            "redirectStart": 0, "redirectEnd": 0, "fetchStart": now,
            "domainLookupStart": now, "domainLookupEnd": now, "connectStart": now,
            "connectEnd": now, "secureConnectionStart": now, "requestStart": now,
            "responseStart": now, "responseEnd": now, "domLoading": now,
            "domInteractive": now, "domContentLoadedEventStart": now,
            "domContentLoadedEventEnd": now, "domComplete": now,
            "loadEventStart": now, "loadEventEnd": now
        } },
        "end": now,
        "timeToSubmit": 108873,
        "form": {
            "email": {
                "keys": 0, "keyPressTimeIntervals": [], "copies": 0, "cuts": 0,
                "pastes": 0, "clicks": 0, "touches": 0, "mouseClickPositions": [],
                "keyCycles": [], "mouseCycles": [], "touchCycles": [],
                "width": 290, "height": 43, "checksum": "C860E86B", "time": 12773,
                "autocomplete": false, "prefilled": false
            },
            "password": {
                "keys": 0, "keyPressTimeIntervals": [], "copies": 0, "cuts": 0,
                "pastes": 0, "clicks": 0, "touches": 0, "mouseClickPositions": [],
                "keyCycles": [], "mouseCycles": [], "touchCycles": [],
                "width": 290, "height": 43, "checksum": "18CFFFC6", "time": 21043,
                "autocomplete": false, "prefilled": false
            }
        }
    })
    .to_string()
}

#[cfg(test)]
fn xxtea_decrypt(v: &mut [u32], key: &[u32; 4]) {
    let n = v.len();
    if n < 2 {
        return;
    }
    let rounds = 6 + 52 / n;
    let mut sum = (rounds as u32).wrapping_mul(DELTA);
    let mut y = v[0];
    while sum != 0 {
        let e = (sum >> 2) & 3;
        for p in (1..n).rev() {
            let z = v[p - 1];
            v[p] = v[p].wrapping_sub(mx(z, y, sum, p, e, key));
            y = v[p];
        }
        let z = v[n - 1];
        v[0] = v[0].wrapping_sub(mx(z, y, sum, 0, e, key));
        y = v[0];
        sum = sum.wrapping_sub(DELTA);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crc32_matches_zlib() {
        assert_eq!(crc32(b"audible-rs"), 0xDC82_FBB8);
        assert_eq!(crc32(b""), 0);
    }

    #[test]
    fn encrypt_metadata_matches_reference_vector() {
        // Cross-checked against the Python `audible` metadata1 (whose key +
        // algorithm decrypt a live, Amazon-accepted value).
        assert_eq!(
            encrypt_metadata("audible-rs"),
            "ECdITeCs:yGBVzisZJvw/L1u7ZYdWgurfLTU="
        );
        assert_eq!(encrypt_metadata("x"), "ECdITeCs:Oo8+0npaF9M+CLRR");
    }

    #[test]
    fn xxtea_round_trips() {
        let plain = "the quick brown fox jumps over the lazy dog 1234";
        let mut longs = bytes_to_longs(plain.as_bytes());
        xxtea_encrypt(&mut longs, &KEY);
        xxtea_decrypt(&mut longs, &KEY);
        let mut out = longs_to_bytes(&longs);
        while out.last() == Some(&0) {
            out.pop();
        }
        assert_eq!(out, plain.as_bytes());
    }

    #[test]
    fn meta_audible_app_is_valid_json_with_inputs() {
        let json = meta_audible_app("UA/1.0", "https://www.amazon.de/ap/signin?x=1");
        let value: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(value["userAgent"], "UA/1.0");
        assert_eq!(value["location"], "https://www.amazon.de/ap/signin?x=1");
        assert_eq!(value["version"], "3.0.0");
        // Encrypting the template yields the prefixed form.
        assert!(encrypt_metadata(&json).starts_with("ECdITeCs:"));
    }
}
